source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'FHStarterProject.xcodeproj'
platform :ios, '7.0'
use_frameworks!

pod 'FeedHenry', :path => '../../'
# TODO delete AeroGearHttp when swift2-0 is realesed as defined as transitive dependency of FeedHenry
pod 'AeroGearHttp', :git => 'https://github.com/aerogear/aerogear-ios-http', :branch => 'swift-2.0'
pod 'SwiftyJSON', :git => 'https://github.com/corinnekrych/SwiftyJSON', :branch => 'xcode7.ios7'